# dfc-shared pipeline
# contains release stages that have a condition set to false (so they never run)
# these can be enabled again when YAML releases are production ready 

variables:
- name: SolutionBaseName
  value: Dfc.Shared

resources:
  repositories:
  - repository: self
  - repository: dfc-devops
    type: github
    name: SkillsFundingAgency/dfc-devops
    endpoint: GitHub
    ref: refs/tags/v2.0.0

pr:
  branches:
    include:
    - master

pool:
  name: windows-latest

stages:

- stage: Build
  jobs:
  - job: TestAndPublish
    steps:
    # ARM template
    - template: AzureDevOpsTemplates/Build/StepTemplates/dfc-arm-build.yml@dfc-devops
      parameters:
        ArmTemplateRoot: '$(System.DefaultWorkingDirectory)\Resources'
        SolutionBaseName: $(SolutionBaseName)
        TokenizeTestParameters: true
    - task: CopyFiles@2
      displayName: 'Copy PSScripts Files to: $(Build.ArtifactStagingDirectory)'
      inputs:
        Contents: 'PSScripts/**/*.ps1'
        TargetFolder: '$(Build.ArtifactStagingDirectory)/Resources/PSScripts'
        flattenFolders: true
    - task: PublishPipelineArtifact@0
      displayName: Publish PSScripts Pipeline Artifact
      inputs:
        targetPath: $(Build.ArtifactStagingDirectory)/Resources/PSScripts
        artifactName: Dfc.Shared.Resources.PSScripts
